import { images } from "./images";

export const dummyMusicData: Music[] = [
    {
      id: "1",
      name: "Eclipse of Time",
      coverImage: images.link,
      duration: 245,
      artists: [{ id: "1", name: "Nova Lane" }],
      audio: "https://example.com/audio/eclipse.mp3",
      likes: 3021,
      musicVibrantColor: "#ea341b",
    },
    {
      id: "2",
      name: "Moonlight Drive",
      coverImage: images.deanLewis,
      duration: 198,
      artists: [{ id: "2", name: "The Silhouettes" }],
      lyrics: "Cruising under the moonlight sky...",
      audio: "https://example.com/audio/moonlight.mp3",
      likes: 4512,
      video: "https://example.com/video/moonlight.mp4",
      musicVibrantColor: "#e48e51",
    },
    {
        id:"4",
      name: "Neon Rain",
      coverImage: images.diffrentWorlds,
      duration: 215,
      artists: [{ id: "3", name: "Echo Drift" }],
      lyrics: "Neon lights reflecting in the rain...",
      audio: "https://example.com/audio/neon.mp3",
      likes: 1987,
      musicVibrantColor: "#b4954c",
    },
    {
      id: "3",
      name: "City Pulse",
      coverImage: images.faded,
      duration: 180,
      artists: [{ id: "4", name: "MetroVibe" }],
      lyrics: "Feel the city pulse in your veins...",
      audio: "https://example.com/audio/citypulse.mp3",
      likes: 3678,
      musicVibrantColor: "#34646c",
    },
    {
        id: "6",
      name: "Waves and Whispers",
      coverImage: images.ignite,
      duration: 230,
      artists: [{ id: "5", name: "Luna Echo" }],
      lyrics: "Waves crash as whispers fade...",
      audio: "https://example.com/audio/waves.mp3",
      likes: 4200,
      musicVibrantColor: "#f27e62",
    },
    {
        id: "7",
      name: "Crimson Skies",
      coverImage: images.janjiheroes,
      duration: 205,
      artists: [{ id: "6", name: "Scarlet Dawn" }],
      lyrics: "Under crimson skies we rise...",
      audio: "https://example.com/audio/crimson.mp3",
      likes: 2890,
      video: "https://example.com/video/crimson.mp4",
      musicVibrantColor:"#4f70af",
    },
    {
        id: "5",
      name: "Static Love",
      coverImage: images.justineBiber,
      duration: 190,
      artists: [
        { id: "7", name: "Electric Soul" },
        { id: "8", name: "Digital Dream" },
      ],
      lyrics: "In static love, we found our tune...",
      audio: "https://example.com/audio/static.mp3",
      likes: 3399,
      musicVibrantColor: "#0cf4ec",
    },
    {
        id: "12",
      name: "Golden Hour",
      coverImage: images.lunax,
      duration: 210,
      artists: [{ id: "9", name: "Amber Skies" }],
      lyrics: "The golden hour glows with love...",
      audio: "https://example.com/audio/goldenhour.mp3",
      likes: 5123,
      musicVibrantColor:"#ec6c07",
    },
    {
        id: "10",
      name: "Mirror Maze",
      coverImage:images.mziki,
      duration: 222,
      artists: [{ id: "10", name: "Glass House" }],
      lyrics: "Caught in a mirror maze of dreams...",
      audio: "https://example.com/audio/mirror.mp3",
      likes: 2770,
      musicVibrantColor:"#0494f4",
    },
    {
      id: "11",
      name: "Digital Horizon",
      coverImage: images.walker,
      duration: 250,
      artists: [{ id: "11", name: "CodeFlow" }],
      lyrics: "Beyond the digital horizon we fly...",
      audio: "https://example.com/audio/horizon.mp3",
      likes: 3680,
      musicVibrantColor: "#1c5c64",
      video: "https://example.com/video/horizon.mp4",
    },
  ];
  